# Generated by Django 3.2 on 2021-04-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
    ]
