# Generated by Django 3.2 on 2021-04-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_exercise_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='bodypart',
            new_name='primary_musclegroup',
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_musclegroup',
            field=models.CharField(blank=True, choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Legs', 'Legs'), ('Cardio', 'Cardio')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
