# Generated by Django 3.2 on 2021-04-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210419_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary_musclegroup',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Quads', 'Quads'), ('Hamstrings', 'Hamstrings'), ('Calves', 'Calves'), ('Cardio', 'Cardio')], max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_musclegroup',
            field=models.CharField(blank=True, choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Quads', 'Quads'), ('Hamstrings', 'Hamstrings'), ('Calves', 'Calves'), ('Cardio', 'Cardio')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('created', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise')),
            ],
        ),
    ]
