# Generated by Django 3.2 on 2021-04-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210422_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='number_of_sets',
            field=models.IntegerField(default=3),
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.ManyToManyField(to='core.Exercise'),
        ),
        migrations.RemoveField(
            model_name='workout',
            name='set',
        ),
        migrations.AddField(
            model_name='workout',
            name='set',
            field=models.ManyToManyField(to='core.Set'),
        ),
    ]
