# Generated by Django 3.2 on 2021-04-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210426_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='primary_musclegroup',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_musclegroup',
        ),
        migrations.RemoveField(
            model_name='set',
            name='number_of_sets',
        ),
        migrations.AlterField(
            model_name='set',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
