# Generated by Django 3.2 on 2021-04-27 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210427_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='created',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='set',
        ),
        migrations.AddField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 27, 12, 53, 0, 194501, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
