# Generated by Django 3.2 on 2021-04-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210427_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.workout'),
            preserve_default=False,
        ),
    ]
